### ISSUE TITLE
Preview in designer window generate StackException

### ISSUE THREAD

**Issue by GuitarKingPaolo** [quicoli/LottieSharp#45]
Unable to parse composition
StackTrace  

 at LottieSharp.LottieAnimationView.SetAnimationAsync(String assetName)
   at LottieSharp.LottieAnimationView.FileNamePropertyChangedCallback(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

i simply have this code:
<Grid Grid.Row="0" Margin="25,25,25,25">
                    <lottieSharp:LottieAnimationView 
                    x:Name="LottieAnimationView" 
                    DefaultCacheStrategy="None" 
                    FileName="logo-anim.json" AutoPlay="True" 
                    VerticalAlignment="Center" 
                    HorizontalAlignment="Center"/>
</Grid>

**Comment by keytrap-x86** [comment]
Same over here. When you start the app it runs fine though
